//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkforceManagementAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skills
    {
        public int SkillID { get; set; }
        public string SkillName { get; set; }
        public string SkillDescription { get; set; }
        public System.DateTime SkillDateOfCreation { get; set; }

        public static explicit operator Skills(Employees v)
        {
            throw new NotImplementedException();
        }
    }
}
